/* claudboard mock data */
/* eslint-disable */
window.DATA = {
  // Workspace-level setup state — feature-workflow gate is per-workspace
  setup: {
    workflowInstalled: true,       // .claude/skills/feature-workflow/ present
    foundationDone: 3,             // analyse + generate + workflow
    foundationTotal: 3,
    repoReadiness: {               // per-repo foundation progress
      datahandler: { done: 3, total: 3, hasWorkflow: true },
      controller:  { done: 3, total: 3, hasWorkflow: true },
      "common-dto":{ done: 3, total: 3, hasWorkflow: true },
      claudboard:  { done: 3, total: 3, hasWorkflow: true },
      "worca-cc":  { done: 2, total: 3, hasWorkflow: false },
      "azure-devops-mcp": { done: 0, total: 3, hasWorkflow: false },
    },
  },
  workspaces: [
    {
      id: "meas",
      name: "meas",
      kind: "workspace",
      mark: "M",
      path: "~/work/meas/",
      repoCount: 6,
    },
    {
      id: "claudboard",
      name: "claudboard",
      kind: "repo",
      mark: "cb",
      path: "~/dev/claudboard/",
    },
  ],

  projects: [
    {
      id: "claudboard",
      name: "claudboard",
      kind: "repo",
      mark: "cb",
      path: "~/dev/claudboard/",
      stack: "TypeScript · MCP",
      defaultBranch: "main",
      lastAnalysed: "2d ago",
      readiness: ["g","g","g","g","g"],
      lastRunStatus: "merged",
      lastRunTitle: "PLAT-4821 · Add /refresh stale-rule detection",
      lastRunAgo: "47m",
    },
    {
      id: "datahandler",
      name: "meas.cloud.datahandler",
      kind: "repo",
      mark: "dh",
      path: "~/work/meas/datahandler/",
      stack: "Java 21 · Spring Boot 3 · MongoDB · Kafka",
      defaultBranch: "main",
      lastAnalysed: "4h ago",
      readiness: ["g","g","g","a","g"],
      lastRunStatus: "running",
      lastRunTitle: "MEAS-7140 · Outbox dispatcher for entitlement events",
      lastRunAgo: "13m",
    },
    {
      id: "controller",
      name: "meas.cloud.controller",
      kind: "repo",
      mark: "ct",
      path: "~/work/meas/controller/",
      stack: "Java 21 · Spring Boot 3 · JPA",
      defaultBranch: "main",
      lastAnalysed: "1d ago",
      readiness: ["g","g","a","g","g"],
      lastRunStatus: "review",
      lastRunTitle: "MEAS-7138 · Tenant‑scoped audit log endpoint",
      lastRunAgo: "2h",
    },
    {
      id: "common-dto",
      name: "meas.cloud.common-dto",
      kind: "repo",
      mark: "dt",
      path: "~/work/meas/common-dto/",
      stack: "Java 21 · Library",
      defaultBranch: "main",
      lastAnalysed: "5d ago",
      readiness: ["g","g","g","g","r"],
      lastRunStatus: "merged",
      lastRunTitle: "MEAS-7102 · Add PaymentMethodDto v2",
      lastRunAgo: "1d",
    },
    {
      id: "azure-devops-mcp",
      name: "azure-devops-mcp",
      kind: "repo",
      mark: "ad",
      path: "~/dev/azure-devops-mcp/",
      stack: "TypeScript · MCP server",
      defaultBranch: "main",
      lastAnalysed: "—",
      readiness: ["a","r","r","r","r"],
      lastRunStatus: "idle",
      lastRunTitle: "—",
      lastRunAgo: "—",
    },
    {
      id: "worca-cc",
      name: "worca-cc",
      kind: "repo",
      mark: "wc",
      path: "~/dev/worca-cc/",
      stack: "Python · multi‑agent orchestration",
      defaultBranch: "main",
      lastAnalysed: "11d ago",
      readiness: ["g","g","a","a","g"],
      lastRunStatus: "merged",
      lastRunTitle: "WC-244 · Replace asyncio.gather with TaskGroup",
      lastRunAgo: "6d",
    },
  ],

  prereqs: [
    {
      id: "analyse",
      title: "Analyse",
      cmd: "/analyse",
      desc: "Read‑only scan: detect patterns, anti‑patterns, workflow signals, and quality.",
      state: "done",
      imported: true,
      requires: [],
      lane: "foundation",
      step: 1,
      lastRun: "2026‑05‑16 14:02",
      ago: "2d ago",
      duration: "3m 14s",
      output: ".claude/reports/claudboard-analysis.md",
      cost: "$0.42",
    },
    {
      id: "generate",
      title: "Generate",
      cmd: "/generate",
      desc: "Render CLAUDE.md, rules with paths: frontmatter, and full‑scope skills from the analysis report.",
      state: "done",
      imported: false,
      requires: ["analyse"],
      lane: "foundation",
      step: 2,
      lastRun: "2026‑05‑16 14:11",
      ago: "2d ago",
      duration: "1m 48s",
      output: "CLAUDE.md · .claude/rules/ · .claude/skills/",
      cost: "$0.18",
    },
    {
      id: "workflow",
      title: "Feature‑workflow",
      cmd: "/claudboard-workflow",
      desc: "Generate the .claude/skills/feature-workflow/ orchestrator skill — agents, scripts, config.json. Required for any feature run.",
      state: "done",
      imported: false,
      requires: ["generate"],
      lane: "foundation",
      step: 3,
      lastRun: "2026‑05‑16 14:18",
      ago: "2d ago",
      duration: "42s",
      output: ".claude/skills/feature-workflow/",
      cost: "$0.06",
      installsWorkflow: true,
    },
    {
      id: "refresh",
      title: "Refresh",
      cmd: "/refresh",
      desc: "Delta update: compare current code against existing artifacts; flag stale or missing rules.",
      state: "stale",
      imported: false,
      requires: ["generate"],
      lane: "maintenance",
      lastRun: "—",
      ago: "never",
      duration: "—",
      output: "—",
      cost: "—",
      note: "Recommended — 17 files changed since last analyse.",
    },
    {
      id: "techdebt",
      title: "Tech debt",
      cmd: "/techdebt",
      desc: "Deep tech debt analysis with module‑grouped, ticket‑ready reports — severity, effort, fix suggestions.",
      state: "missing",
      imported: false,
      requires: ["analyse"],
      lane: "maintenance",
      lastRun: "—",
      ago: "never",
      duration: "—",
      output: "—",
      cost: "—",
      note: "Not yet run for this repo.",
    },
  ],

  // active feature-workflow run
  run: {
    ticket: "MEAS-7140",
    title: "Outbox dispatcher for entitlement events",
    branch: "feature/MEAS-7140/outbox-dispatcher-entitlement-events",
    repo: "meas.cloud.datahandler",
    started: "2026-05-18 09:47",
    elapsed: "13m 28s",
    elapsedSec: 808,
    cost: 0.84,
    tokensIn: 124300,
    tokensOut: 18950,
    status: "gate", // gate | running | review | done | failed
    progress: 28,
    phases: [
      {
        id: "p1",
        num: "1",
        title: "Ticket · Clarify · Specify · Plan",
        status: "active",
        elapsed: "12m 04s",
        agents: [
          { id: "jira-create",   name: "jira-agent",    op: "create",            status: "done",   dur: "0:21" },
          { id: "clarify",       name: "main",          op: "clarify scope",     status: "done",   dur: "3:42" },
          { id: "jira-update",   name: "jira-agent",    op: "updateDescription", status: "done",   dur: "0:18" },
          { id: "sdd",           name: "sdd-expert",    op: "BDD spec",          status: "done",   dur: "4:11" },
          { id: "architect",     name: "architect",     op: "execution plan",    status: "done",   dur: "3:32" },
          { id: "gate",          name: "user",          op: "spec + plan approval", status: "gate",  dur: "—" },
        ],
      },
      {
        id: "p2",
        num: "2",
        title: "Create branch",
        status: "pending",
        elapsed: "—",
        agents: [
          { id: "git-branch", name: "git-agent", op: "create-branch", status: "pending", dur: "—" },
        ],
      },
      {
        id: "p3",
        num: "3",
        title: "Develop · Checkpoints (4)",
        status: "pending",
        elapsed: "—",
        agents: [
          { id: "impl-base", name: "implementation", op: "baseline verify",   status: "pending", dur: "—" },
          { id: "impl-1",    name: "implementation", op: "checkpoint 1 — OutboxEvent entity + repo", status: "pending", dur: "—" },
          { id: "impl-2",    name: "implementation", op: "checkpoint 2 — dispatcher worker",          status: "pending", dur: "—" },
          { id: "impl-3",    name: "implementation", op: "checkpoint 3 — Kafka producer wiring",      status: "pending", dur: "—" },
          { id: "impl-4",    name: "implementation", op: "checkpoint 4 — integration tests",          status: "pending", dur: "—" },
        ],
      },
      {
        id: "p4",
        num: "4",
        title: "Commit",
        status: "pending",
        elapsed: "—",
        agents: [
          { id: "git-commit", name: "git-agent", op: "squash + stage + commit", status: "pending", dur: "—" },
        ],
      },
      {
        id: "p5",
        num: "5",
        title: "Review",
        status: "pending",
        elapsed: "—",
        agents: [
          { id: "spec-rev",   name: "spec-reviewer",   op: "BDD scenario coverage", status: "pending", dur: "—" },
          { id: "design-rev", name: "design-reviewer", op: "rules + conventions",   status: "pending", dur: "—" },
        ],
      },
      {
        id: "p6",
        num: "6",
        title: "Pull request",
        status: "pending",
        elapsed: "—",
        agents: [
          { id: "pr",       name: "pr-agent",   op: "open ADO pull request", status: "pending", dur: "—" },
        ],
      },
      {
        id: "p7",
        num: "7",
        title: "Finalize",
        status: "pending",
        elapsed: "—",
        agents: [
          { id: "jira-done", name: "jira-agent", op: "transition + worklog",  status: "pending", dur: "—" },
        ],
      },
    ],
    stream: [
      { t: "09:47:02", ag: "main",        msg: "Workflow started · ticket=MEAS-7140", cls: "user" },
      { t: "09:47:03", ag: "main",        msg: "Loaded config.json · projectKey=MEAS · branchPattern={type}/{ticket}/{slug}" },
      { t: "09:47:04", ag: "jira-agent",  msg: "→ atlassian.createIssue project=MEAS type=Story", cls: "tool" },
      { t: "09:47:23", ag: "jira-agent",  msg: "Created MEAS-7140 · labels=[AI, AI_CLI, backend]", cls: "ok" },
      { t: "09:47:24", ag: "main",        msg: "Phase 1a · clarify scope" },
      { t: "09:47:25", ag: "main",        msg: "→ user: confirmed scope (outbox dispatcher only, no schema registry)" },
      { t: "09:50:46", ag: "jira-agent",  msg: "→ atlassian.updateIssue MEAS-7140 description=…", cls: "tool" },
      { t: "09:51:04", ag: "jira-agent",  msg: "Updated MEAS-7140 · description=4 paragraphs · 2 acceptance criteria", cls: "ok" },
      { t: "09:51:05", ag: "main",        msg: "Phase 1b · sdd-expert-agent (BDD specification)" },
      { t: "09:51:06", ag: "sdd-expert",  msg: "Reading .claude/rules/testing-rules.md · .claude/skills/integration-test/SKILL.md" },
      { t: "09:53:11", ag: "sdd-expert",  msg: "Drafted 3 scenarios · 14 Given/When/Then steps" },
      { t: "09:55:16", ag: "sdd-expert",  msg: "Wrote outbox-dispatcher.feature · 142 LOC", cls: "ok" },
      { t: "09:55:17", ag: "main",        msg: "Phase 1c · architect-agent (execution plan)" },
      { t: "09:55:18", ag: "architect",   msg: "Reading .claude/rules/mongodb-conventions.md · .claude/rules/kafka-producer.md" },
      { t: "09:58:48", ag: "architect",   msg: "Identified OpenAPI changes: none. DB: 1 new collection (outbox_events)." },
      { t: "09:58:49", ag: "architect",   msg: "Decomposed into 4 checkpoints · est. 3.5h" },
      { t: "09:58:50", ag: "architect",   msg: "Wrote plan.md · 4 checkpoints, 11 tasks, 7 contracts", cls: "ok" },
      { t: "09:58:51", ag: "main",        msg: "Phase 1d · spec + plan approval", cls: "gate" },
      { t: "09:58:52", ag: "main",        msg: "⏸  Waiting for user approval to enter autonomous mode", cls: "gate" },
    ],
  },

  // gate review content
  gate: {
    ticket: "MEAS-7140",
    title: "Outbox dispatcher for entitlement events",
    spec: [
      { kind: "feature", text: "Feature: Outbox dispatcher for entitlement events" },
      { kind: "comment", text: "  # Persist domain events to an outbox table, then dispatch to Kafka" },
      { kind: "comment", text: "  # exactly-once. Survives broker outages without losing events." },
      { kind: "blank" },
      { kind: "scenario", text: "Scenario: New entitlement granted is persisted to the outbox" },
      { kind: "step", keyword: "Given", text: "a tenant ", arg: "\"acme\"", tail: " with a valid plan" },
      { kind: "and",  keyword: "And",   text: "no outbox events exist for tenant ", arg: "\"acme\"", tail: "" },
      { kind: "step", keyword: "When",  text: "an entitlement ", arg: "\"reports.export\"", tail: " is granted" },
      { kind: "and",  keyword: "Then",  text: "an outbox event of type ", arg: "\"EntitlementGranted\"", tail: " is created" },
      { kind: "and",  keyword: "And",   text: "the event status is ", arg: "\"PENDING\"", tail: "" },
      { kind: "and",  keyword: "And",   text: "the event payload includes the tenant id, plan id, and entitlement key", tail: "" },
      { kind: "blank" },
      { kind: "scenario", text: "Scenario: Dispatcher publishes pending events to Kafka in FIFO order" },
      { kind: "step", keyword: "Given", text: "3 outbox events with status ", arg: "\"PENDING\"", tail: " for tenant ", arg2: "\"acme\"" },
      { kind: "and",  keyword: "When",  text: "the dispatcher tick fires" },
      { kind: "and",  keyword: "Then",  text: "all 3 events are produced to topic ", arg: "\"entitlement.events.v1\"", tail: "" },
      { kind: "and",  keyword: "And",   text: "the produced records carry the tenant id as the partition key" },
      { kind: "and",  keyword: "And",   text: "each event status transitions to ", arg: "\"DISPATCHED\"", tail: "" },
      { kind: "blank" },
      { kind: "scenario", text: "Scenario: Broker outage keeps events PENDING and retries on next tick" },
      { kind: "step", keyword: "Given", text: "the Kafka broker is unavailable" },
      { kind: "and",  keyword: "And",   text: "5 outbox events with status ", arg: "\"PENDING\"", tail: "" },
      { kind: "and",  keyword: "When",  text: "the dispatcher tick fires" },
      { kind: "and",  keyword: "Then",  text: "no event status changes" },
      { kind: "and",  keyword: "And",   text: "a warning is logged with cause ", arg: "\"broker_unavailable\"", tail: "" },
      { kind: "and",  keyword: "And",   text: "the next tick after recovery dispatches all 5 events" },
    ],
    plan: [
      {
        num: 1,
        title: "OutboxEvent entity + repository",
        desc: "Add @Document OutboxEvent with id, tenantId, type, payload, status, createdAt, dispatchedAt. Reactive repo with findPendingByTenant().",
        files: ["domain/outbox/OutboxEvent.java", "domain/outbox/OutboxEventRepository.java", "adapter/persistence/MongoOutboxEventAdapter.java"],
        contracts: ["DB collection: outbox_events"],
      },
      {
        num: 2,
        title: "Dispatcher worker (scheduled tick)",
        desc: "Spring @Scheduled component that locks-and-claims pending events, batches by tenant, and hands off to the producer port.",
        files: ["application/outbox/OutboxDispatcher.java", "application/outbox/OutboxDispatcherProperties.java"],
        contracts: ["Port: OutboxProducerPort.publish(OutboxEvent) → Mono<Void>"],
      },
      {
        num: 3,
        title: "Kafka producer wiring",
        desc: "Implement OutboxProducerPort with KafkaTemplate. Partition key = tenantId. Topic from configuration.",
        files: ["adapter/messaging/KafkaOutboxProducerAdapter.java", "config/KafkaProducerConfig.java"],
        contracts: ["Topic: entitlement.events.v1 · key: tenantId"],
      },
      {
        num: 4,
        title: "Integration tests",
        desc: "Spock + EmbeddedKafka + Testcontainers Mongo. Cover all 3 BDD scenarios including the outage retry path.",
        files: ["src/test/groovy/.../OutboxDispatcherIntegrationSpec.groovy"],
        contracts: [],
      },
    ],
  },
};
